base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Base
import stock
from base import views
from base.views import DashboardView, DataTablesTranslationsJsonView

# Clinic
import clinic
from clinic import urls

# Scheduling
import scheduling
from scheduling import urls

# Consultation
import consultation
from consultation import urls

# Stock
import stock
from stock import urls

# Invoicing
import invoicing
from invoicing import urls

# Reports
import reports.urls


urlpatterns = [
    # Base URLs
    path('login/', views.Login.as_view(), name='login'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Datatables translation
    path('datatables_translation', DataTablesTranslationsJsonView.as_view(), name='datatables_translation'),

    # Clinic URLs
    path('clinic/', include(clinic.urls)),

    # Scheduling URLs
    path('scheduling/', include(scheduling.urls)),

    # Consultation URLs
    path('consultation/', include(consultation.urls)),

    # Stock URLs
    path('stock/', include(stock.urls)),

    # Invoicing URLs
    path('invoicing/', include(invoicing.urls)),

    # Reports URLs
    path('reports/', include(reports.urls)),

]

reports/urls.py
from django.urls import path
from reports.views import CashReportListView, ReportingDoctorsReportListView, TreatingDoctorsReportListView, InsurancesAgreementsReportListView, ConsultationSheetTotalReportListView, \
    ReportDefinitionListView, ReportDefinitionCreateView, ReportDefinitionUpdateView, RunReportView, SaveReportView, InvoiceReportListView

urlpatterns = [
    # Cash Report
    path('cash_report_list/', CashReportListView.as_view(), name='reports.cash_report_list'),

    # Invoice Report
    path('invoice_report_list/', InvoiceReportListView.as_view(), name='reports.invoice_report_list'),

    # Reporting Doctors Report
    path('reporting_doctors_report_list/', ReportingDoctorsReportListView.as_view(), name='reports.reporting_doctors_report_list'),

    # Treating Doctors Report
    path('treating_doctors_report_list/', TreatingDoctorsReportListView.as_view(), name='reports.treating_doctors_report_list'),

    # Insurances Agreements Report
    path('insurances_agreements_report_list/', InsurancesAgreementsReportListView.as_view(), name='reports.insurances_agreements_report_list'),

    # Consultation Sheet Total Report
    path('consultation_sheet_total_report_list/', ConsultationSheetTotalReportListView.as_view(), name='reports.consultation_sheet_total_report_list'),

    # List Reports Definitions
    path('reports_definition_list/', ReportDefinitionListView.as_view(), name='reports.reports_definition_list'),

    # Create Report Definition
    path('report_definition/create/', ReportDefinitionCreateView.as_view(), name='reports.report_definition.create'),

    # Update Report Definition
    path('report_definition/update/<int:pk>', ReportDefinitionUpdateView.as_view(), name='reports.report_definition.update'),

    # Report Save
    path('save_report/<int:pk>/', SaveReportView.as_view(), name='reports.report_definition.save'),

    # Report Run
    path('run_report/', RunReportView.as_view(), name='reports.report_definition.run'),



]

sistema/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from sistema import settings

admin.site.site_header = "Sistema Iribas Admin"
admin.site.site_title = "Sistema Iribas Portal"
admin.site.index_title = "Bienvenido al administrador del Sistema Iribas"

urlpatterns = [
                  path('admin/', admin.site.urls,),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('base.urls')),
              ]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'sistema.views.handler404'
# handler500 = 'sistema.views.handler500'

reports/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# store report requests for testing, used by ReportBro Designer
# for preview of pdf and xlsx
class ReportRequest(models.Model):
    key = models.CharField(max_length=36)
    report_definition = models.TextField()
    data = models.TextField()
    is_test_data = models.BooleanField()
    pdf_file = models.BinaryField(null=True)
    pdf_file_size = models.IntegerField(null=True)
    created_on = models.DateTimeField()

    class Meta:
        verbose_name = _("Report Request")
        verbose_name_plural = _("Reports Requests")


# report definition for our album report which is used for printing
# the pdf with the album list. When the report is saved
# in ReportBro Designer it will be stored in this table.
class ReportDefinition(models.Model):
    report_definition = models.TextField()
    report_type = models.CharField(max_length=30)
    remark = models.TextField(null=True)
    last_modified_at = models.DateTimeField()

    class Meta:
        verbose_name = _("Report Definition")
        verbose_name_plural = _("Reports Definitions")

    def __str__(self):
        desc = self.report_type
        if self.remark:
            desc += ', ' + self.remark
        desc += ' (' + str(self.last_modified_at) + ')'
        return desc

reports/forms.py
from django import forms
from clinic.models import Doctor, TreatingDoctor, InsurancePlan, Sector, MedicalStudyType, MedicalStudy, MedicalEquipment, Patient
from django.utils.translation import ugettext_lazy as _

from invoicing.models import PaymentMethod, IssuingCompanyName, Customer


class CashReportFiltersForm(forms.Form):
    HTML_TYPE = 1
    EXCEL_TYPE = 2
    PDF_TYPE = 3

    REPORTS_TYPES = (
        (HTML_TYPE, _('Web')),
        (EXCEL_TYPE, _('Excel')),
        (PDF_TYPE, _('Pdf')),
    )

    date_time_start = forms.DateTimeField(
        label=_('Date Time Start Filter'),
        required=False,
    )
    date_time_end = forms.DateTimeField(
        label=_('Date Time End Filter'),
        required=False,
    )
    payment_method = forms.ModelChoiceField(
        queryset=PaymentMethod.objects.all(),
        label=_('Payment Method'),
        required=False
    )
    study_type = forms.ModelChoiceField(
        label=_('Medical Study Type'),
        queryset=MedicalStudyType.objects.all(),
        required=False
    )
    report_type = forms.ChoiceField(
        label=_('Report Type'),
        choices=REPORTS_TYPES,
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(CashReportFiltersForm, self).__init__(*args, **kwargs)


class InvoiceReportFiltersForm(forms.Form):
    HTML_TYPE = 1
    EXCEL_TYPE = 2
    ABACO_TYPE = 3

    REPORTS_TYPES = (
        (HTML_TYPE, _('Web')),
        (EXCEL_TYPE, _('Excel')),
        (ABACO_TYPE, _('Abaco')),
    )

    PAYMENT_TERM = (
        ('', '-------'),
        ('CONTADO', 'CONTADO'),
        ('CREDITO', 'CREDITO')
    )

    date_time_start = forms.DateField(
        label=_('Date Time Start Filter'),
        required=True,
    )
    date_time_end = forms.DateField(
        label=_('Date Time End Filter'),
        required=True,
    )
    company_name = forms.ModelChoiceField(
        queryset=IssuingCompanyName.objects.all(),
        label=_('Company Name'),
        required=False
    )
    client = forms.ModelChoiceField(
        queryset=Customer.objects.all(),
        label=_('Cliente'),
        required=False
    )
    payment_term = forms.ChoiceField(
        label=_('Payment Term'),
        choices=PAYMENT_TERM,
        required=False
    )
    report_type = forms.ChoiceField(
        label=_('Report Type'),
        choices=REPORTS_TYPES,
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(InvoiceReportFiltersForm, self).__init__(*args, **kwargs)


class ReportingDoctorsReportFiltersForm(forms.Form):
    HTML_TYPE = 1
    EXCEL_TYPE = 2
    PDF_TYPE = 3

    REPORTS_TYPES = (
        (HTML_TYPE, _('Web')),
        (EXCEL_TYPE, _('Excel')),
        (PDF_TYPE, _('Pdf')),
    )
    date_time_start = forms.DateTimeField(
        label=_('Date Time Start Filter'),
        required=False,
    )
    date_time_end = forms.DateTimeField(
        label=_('Date Time End Filter'),
        required=False,
    )
    reporting_doctor = forms.ModelChoiceField(
        label=_('Reporting Doctor'),
        required=False,
        queryset=Doctor.objects.all()
    )
    sector = forms.ModelChoiceField(
        label=_('Sector'),
        required=False,
        queryset=Sector.objects.all()
    )
    report_type = forms.ChoiceField(
        label=_('Report Type'),
        choices=REPORTS_TYPES,
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(ReportingDoctorsReportFiltersForm, self).__init__(*args, **kwargs)


class TreatingDoctorsReportFiltersForm(forms.Form):
    HTML_TYPE = 1
    EXCEL_TYPE = 2
    PDF_TYPE = 3

    REPORTS_TYPES = (
        (HTML_TYPE, _('Web')),
        (EXCEL_TYPE, _('Excel')),
        (PDF_TYPE, _('Pdf')),
    )
    date_time_start = forms.DateTimeField(
        label=_('Date Time Start Filter'),
        required=False,
    )
    date_time_end = forms.DateTimeField(
        label=_('Date Time End Filter'),
        required=False,
    )
    treating_doctor = forms.ModelChoiceField(
        label=_('Treating Doctor'),
        required=False,
        queryset=TreatingDoctor.objects.all()
    )
    sector = forms.ModelChoiceField(
        label=_('Sector'),
        required=False,
        queryset=Sector.objects.all()
    )
    report_type = forms.ChoiceField(
        label=_('Report Type'),
        choices=REPORTS_TYPES,
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(TreatingDoctorsReportFiltersForm, self).__init__(*args, **kwargs)


class InsurancesAgreementsReportFiltersForm(forms.Form):
    HTML_TYPE = 1
    EXCEL_TYPE = 2
    PDF_TYPE = 3

    INSURANCE_ENTRY_SHEETS_TO_PAY_WITHOUT_INVOICES = 1
    INSURANCE_ENTRY_SHEETS_TO_PAY_WITH_INVOICES = 2
    ALL_INSURANCE_ENTRY_SHEETS_TO_PAY = 3


    INVOICES_FILTER_CHOICES = (
        (INSURANCE_ENTRY_SHEETS_TO_PAY_WITHOUT_INVOICES, _('Insurance Entry Sheets To pay without Invoices')),
        (INSURANCE_ENTRY_SHEETS_TO_PAY_WITH_INVOICES, _('Insurance Entry Sheets To pay with Invoices')),
        (ALL_INSURANCE_ENTRY_SHEETS_TO_PAY, _('Al Insurance Entry Sheets To pay')),
    )

    REPORTS_TYPES = (
        (HTML_TYPE, _('Web')),
        (EXCEL_TYPE, _('Excel')),
        (PDF_TYPE, _('Pdf')),
    )
    date_time_start = forms.DateTimeField(
        label=_('Date Time Start Filter'),
        required=False,
    )
    date_time_end = forms.DateTimeField(
        label=_('Date Time End Filter'),
        required=False,
    )
    insurance_plan = forms.ModelChoiceField(
        label=_('Insurance Plan'),
        required=False,
        queryset=InsurancePlan.objects.all()
    )
    sector = forms.ModelChoiceField(
        label=_('Sector'),
        required=False,
        queryset=Sector.objects.all()
    )
    study_type = forms.ModelChoiceField(
        label=_('Medical Study Type'),
        queryset=MedicalStudyType.objects.all(),
        required=False
    )
    report_type = forms.ChoiceField(
        label=_('Report Type'),
        choices=REPORTS_TYPES,
        required=False
    )
    invoice_filter = forms.ChoiceField(
        label=_('Invoice Filter'),
        choices=INVOICES_FILTER_CHOICES,
        required=True
    )

    def __init__(self, *args, **kwargs):
        super(InsurancesAgreementsReportFiltersForm, self).__init__(*args, **kwargs)


class ConsultationSheetsTotalReportFiltersForm(forms.Form):
    HTML_TYPE = 1
    EXCEL_TYPE = 2
    PDF_TYPE = 3

    REPORTS_TYPES = (
        (HTML_TYPE, _('Web')),
        (EXCEL_TYPE, _('Excel')),
        # (PDF_TYPE, _('Pdf')),
    )
    date_time_start = forms.DateTimeField(
        label=_('Date Time Start Filter'),
        required=False,
    )
    date_time_end = forms.DateTimeField(
        label=_('Date Time End Filter'),
        required=False,
    )
    insurance_plan = forms.ModelChoiceField(
        label=_('Insurance Plan'),
        required=False,
        queryset=InsurancePlan.objects.all()
    )
    medical_study = forms.ModelChoiceField(
        label=_('Medical Study'),
        queryset=MedicalStudy.objects.all(),
        required=False
    )
    medical_equipment = forms.ModelChoiceField(
        label=_('Medical Equipment'),
        queryset=MedicalEquipment.objects.all(),
        required=False
    )
    doctor = forms.ModelChoiceField(
        label=_('Doctor'),
        queryset=Doctor.objects.all(),
        required=False
    )
    sector = forms.ModelChoiceField(
        label=_('Sector'),
        required=False,
        queryset=Sector.objects.all()
    )
    study_type = forms.ModelChoiceField(
        label=_('Medical Study Type'),
        queryset=MedicalStudyType.objects.all(),
        required=False
    )
    reporting_doctor = forms.ModelChoiceField(
        label=_('Reporting Doctor'),
        required=False,
        queryset=Doctor.objects.all()
    )
    treating_doctor = forms.ModelChoiceField(
        label=_('Treating Doctor'),
        required=False,
        queryset=TreatingDoctor.objects.all()
    )
    payment_method = forms.ModelChoiceField(
        queryset=PaymentMethod.objects.all(),
        label=_('Payment Method'),
        required=False
    )
    report_type = forms.ChoiceField(
        label=_('Report Type'),
        choices=REPORTS_TYPES,
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(ConsultationSheetsTotalReportFiltersForm, self).__init__(*args, **kwargs)

reports/templates/cash_report/base_pdf.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>{{ title|default:"" }}</title>
    {% block style_base %}
        {% block layout_style %}
            <style>
                @page {
                    size: A4;
                    margin: 0.5cm;
                }
                @media print {
                    .test{
                        width: 300px;
                    }
                }
            </style>
        {% endblock %}
        {% block extra_style %}{% endblock %}
    {% endblock %}
</head>
<body style="font-size: 10px">
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

reports/templates/cash_report/cash_report_list.html
{% extends "layout.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    Reportes
  </h1>

{% endblock %}
{% block content %}

  <!-- DataTables Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Reporte de Caja
      </h6>
      <br>
      <form action="{% url 'reports.cash_report_list' %}" method="get" class="d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100">
        {% csrf_token %}
        {% for field in filter_form %}
          {{ field|as_crispy_field }}
          <br>
        {% endfor %}
        <button type="submit" class="btn btn-primary" id="id_submit_button">Obtener Reporte</button>
      </form>
    </div>
    <div class="card-body">
      <div class="table-responsive">

        <table class="table table-bordered" id="dataTable" style="width: 100%; border-spacing: 0">
          <thead>
          <tr style="text-align: center;">
            <th>ID de Pago</th>
            <th>Fecha Hora</th>
            <th>Paciente</th>
            <th>Seguro</th>
            <th>Servicio</th>
            <th>Empresa</th>
            <th>Método de Pago</th>
            <th>Arancel de Estudio</th>
            <th>Total Insumos</th>
            <th>Descuento</th>
            <th>Total a Pagar Paciente</th>
            <th>Monto Pagado</th>
          </tr>
          </thead>
          <tbody>
          {% for p in payments %}

            <tr style="text-align: center;">
              <td>{{ p.id }}</td>
              <td>
                <span style="display:none;">{{ p.payment_datetime|date:"U" }}</span>
                {{ p.payment_datetime|date:"D d/m/Y H:i" }}
              </td>
              <td>
                <a href="{% url 'patient.detail' p.consultation_sheet.patient.id %}" target="_blank">
                  {{ p.consultation_sheet.patient }}
                </a>
              </td>
              <td>
                {{ p.consultation_sheet.patient_insurance_plan }}
              </td>
              <td>
                <a href="{% url 'consultation_sheet.detail' p.consultation_sheet.id %}" target="_blank">
                  {{ p.consultation_sheet.medical_study }}
                </a>
              </td>
              <td>{{ p.consultation_sheet.medical_study.type }}</td>
              <td>{{ p.consultation_sheet.payment_method|default_if_none:"----" }}</td>
              <td style="text-align: right">{{ p.consultation_sheet.medical_study_ammount }}</td>
              <td style="text-align: right">{{ p.consultation_sheet.medical_supplies_ammount }}</td>
              <td style="text-align: right">{{ p.consultation_sheet.discount }}</td>
              <td style="text-align: right">{{ p.consultation_sheet.total_ammount_to_pay_patient_with_discount }}</td>
              <td style="text-align: right">{{ p.amount }}</td>
            </tr>
          {% endfor %}
          </tbody>
          <tfoot style="text-align: right">
            <th colspan="7"></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_css %}
  <!-- Custom styles for this page -->
  <link type="text/css" href="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
  <link type="text/css" href="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
  <link type="text/css" href="{% static 'build/vendor/chosen-js/chosen.min.css' %}" rel="stylesheet">

{% endblock %}

{% block extra_js %}
  <!-- Page level plugins -->
  <script type="text/javascript" src="{% static 'build/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'base/js/datatables/numeric-comma.js' %}"></script>
  <script type="text/javascript" src="{% static 'build/vendor/moment/moment.js' %}"></script>
  <script type="text/javascript" src="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'base/js/utils.js' %}"></script>
  <script type="text/javascript" src="{% static 'build/vendor/chosen-js/chosen.jquery.min.js' %}"></script>
  <script src="{% static 'build/vendor/jquery-mask-plugin/jquery.mask.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script type="text/javascript">
      $(function () {
          /* Chosen */
          $('select').chosen();

          /* Datetime picker */
          jQuery.datetimepicker.setLocale('es');

          /* Se inicializa el datatables */
          $('#dataTable').DataTable(
              /* Archivo de traducción */
              {
                  language: {
                      url: "{% url 'datatables_translation' %}",
                  },
                  columnDefs: [
                      {type: "numeric-comma", targets: [0, 7, 8, 9, 10, 11]},
                      {
                          data: "Arancel de Estudio",
                          render: $.fn.dataTable.render.number('.', ',', 1, '', ''),
                          targets: 7

                      },
                      {
                          data: "Total Insumos",
                          render: $.fn.dataTable.render.number('.', ',', 1, '', ''),
                          targets: 8

                      },
                      {
                          data: "Descuento",
                          render: $.fn.dataTable.render.number('.', ',', 1, '', ''),
                          targets: 9

                      },
                      {
                          data: "Total",
                          render: $.fn.dataTable.render.number('.', ',', 1, '', ''),
                          targets: 10

                      },
                      {
                          data: "Monto Pagado",
                          render: $.fn.dataTable.render.number('.', ',', 1, '', ''),
                          targets: 11

                      },
                  ],
                  "footerCallback": function (row, data, start, end, display) {
                      var api = this.api(), data;

                      var number_format = $.fn.dataTable.render.number('.', ',', 1, '', '').display;

                      // converting to interger to find total
                      var intVal = function (i) {
                          return typeof i === 'string' ?
                              i.replace(/[\$,]/g, '') * 1 :
                              typeof i === 'number' ?
                                  i : 0;
                      };

                      // computing column Total of the complete result
                      var estudio = api
                          .column(7)
                          .data()
                          .reduce(function (a, b) {
                              let sum = parseFloat(a) + parseFloat(b);
                              return sum
                          }, 0);

                      var materiales = api
                          .column(8)
                          .data()
                          .reduce(function (a, b) {
                              let sum = parseFloat(a) + parseFloat(b);
                              return sum
                          }, 0);

                      var descuento = api
                          .column(9)
                          .data()
                          .reduce(function (a, b) {
                              let sum = parseFloat(a) + parseFloat(b);
                              return sum
                          }, 0);

                      var total = api
                          .column(10)
                          .data()
                          .reduce(function (a, b) {
                              let sum = parseFloat(a) + parseFloat(b);
                              return sum
                          }, 0);

                      var monto_pagado = api
                          .column(11)
                          .data()
                          .reduce(function (a, b) {
                              let sum = parseFloat(a) + parseFloat(b);
                              return sum
                          }, 0);


                      // Update footer by showing the total with the reference of the column index
                      $(api.column(0).footer()).html('Totales:');
                      $(api.column(7).footer()).html(number_format(estudio));
                      $(api.column(8).footer()).html(number_format(materiales));
                      $(api.column(9).footer()).html(number_format(descuento));
                      $(api.column(10).footer()).html(number_format(total));
                      $(api.column(11).footer()).html(number_format(monto_pagado));
                  },

              }
          );

          /* Se inicializan los datetime picker de los filtros */
          /* Si el campo de fecha no está vacío */
          $('#id_date_time_start').mask("00/00/0000 00:00");
          $('#id_date_time_end').mask("00/00/0000 00:00");

          $('#id_date_time_start').click(function (){
              $(this).select();
          });
          $('#id_date_time_end').click(function (){
              $(this).select();
          });

          if ($("#id_date_time_start").val() !== '') {
              var str_fecha = $("#id_date_time_start").val();
              str_fecha = str_fecha.substring(0, 16);
              $("#id_date_time_start").val(str_fecha);
              var fecha_inicio = $("#id_date_time_start").val();

              str_fecha = $("#id_date_time_end").val();
              str_fecha = str_fecha.substring(0, 16);
              $("#id_date_time_end").val(str_fecha);
              var fecha_fin = $("#id_date_time_end").val();

              var fecha_inicio_date = moment(fecha_inicio, 'DD/MM/YYYY HH:mm').toDate();
              var fecha_fin_date = moment(fecha_fin, 'DD/MM/YYYY HH:mm').toDate();

              /* Datetimepicker */
              var datetimepicker_start = $("#id_date_time_start").datetimepicker({
                  i18n: {
                      es: {
                          months: [
                              'Enero', 'Febrero', 'Marzo', 'Abril',
                              'Mayo', 'Junio', 'Julio', 'Agosto',
                              'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                          ],
                          dayOfWeek: [
                              "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa",
                          ]
                      }
                  },
                  lang: 'es',
                  locale: 'es',
                  format: 'd/m/Y H:i',
                  inline: false,
                  step: 15,
                  defaultDate: fecha_inicio_date
              });

              var datetimepicker_end = $("#id_date_time_end").datetimepicker({
                  i18n: {
                      es: {
                          months: [
                              'Enero', 'Febrero', 'Marzo', 'Abril',
                              'Mayo', 'Junio', 'Julio', 'Agosto',
                              'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                          ],
                          dayOfWeek: [
                              "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa",
                          ]
                      }
                  },
                  lang: 'es',
                  locale: 'es',
                  format: 'd/m/Y H:i',
                  inline: false,
                  step: 15,
                  defaultDate: fecha_fin_date
              });


              /* Si el campo de fecha está vacío */
          } else {
              /* Datetimepicker */
              var datetimepicker_start = $("#id_date_time_start").datetimepicker({
                  i18n: {
                      es: {
                          months: [
                              'Enero', 'Febrero', 'Marzo', 'Abril',
                              'Mayo', 'Junio', 'Julio', 'Agosto',
                              'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                          ],
                          dayOfWeek: [
                              "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa",
                          ]
                      }
                  },
                  lang: 'es',
                  locale: 'es',
                  format: 'd/m/Y H:i',
                  inline: false,
                  step: 15,
                  defaultDate: new Date()
              });


              var datetimepicker_end = $("#id_date_time_end").datetimepicker({
                  i18n: {
                      es: {
                          months: [
                              'Enero', 'Febrero', 'Marzo', 'Abril',
                              'Mayo', 'Junio', 'Julio', 'Agosto',
                              'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                          ],
                          dayOfWeek: [
                              "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa",
                          ]
                      }
                  },
                  lang: 'es',
                  locale: 'es',
                  format: 'd/m/Y H:i',
                  inline: false,
                  step: 15,
                  defaultDate: new Date()
              });

          }

      });

  </script>


{% endblock %}