base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Base
import stock
from base import views
from base.views import DashboardView, DataTablesTranslationsJsonView

# Clinic
import clinic
from clinic import urls

# Scheduling
import scheduling
from scheduling import urls

# Consultation
import consultation
from consultation import urls

# Stock
import stock
from stock import urls

# Invoicing
import invoicing
from invoicing import urls

# Reports
import reports.urls


urlpatterns = [
    # Base URLs
    path('login/', views.Login.as_view(), name='login'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Datatables translation
    path('datatables_translation', DataTablesTranslationsJsonView.as_view(), name='datatables_translation'),

    # Clinic URLs
    path('clinic/', include(clinic.urls)),

    # Scheduling URLs
    path('scheduling/', include(scheduling.urls)),

    # Consultation URLs
    path('consultation/', include(consultation.urls)),

    # Stock URLs
    path('stock/', include(stock.urls)),

    # Invoicing URLs
    path('invoicing/', include(invoicing.urls)),

    # Reports URLs
    path('reports/', include(reports.urls)),

]

invoicing/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    # INVOICE
    path('list/', InvoiceDataTableView.as_view(), name='invoice_list'),
    path('details/<int:pk>', InvoiceDetailsView.as_view(), name='invoice_detail'),
    path('create/', InvoiceCreationView.as_view(), name='invoice_create'),
    path('createfromconsultationsheet/<int:consultation_entry_sheet_id>', InvoiceCreationFromConsultationSheetView.as_view(), name='invoice.create.consultationsheet'),
    path('delete/<int:pk>', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('modify/<int:pk>', InvoiceUpdateView.as_view(), name='invoice_update'),
    path('consultafactura/<int:company_id>', InvoiceLastNumber.as_view(), name='invoice.lastnumber'),
    path('print/<int:pk>/', InvoicePrintView.as_view(), name='invoice.print'),
    path('send_invoice_to_sifen/<int:pk>/', InvoiceSendToSifenView.as_view(), name='invoice.send_to_sifen'),
    path('send_invoice_email_to_cliente/<int:pk>/', InvoiceEmailSendToClientView.as_view(), name='invoice.email_send_to_client'),
    path('consultacliente/', CustomerQuery.as_view(), name='customer.query'),
    path('createfrominsurancereport/', InvoiceCreateFromInsuranceReportView.as_view(), name='invoice.create.insurance_report'),
    path('download_invoice_pdf/<int:pk>/', InvoiceDownloadPdfview.as_view(), name='invoice.download_invoice_pdf'),
    path('generate_invoice_pdf_sifen/<int:pk>/', InvoiceGenerateSifenPdfView.as_view(), name='invoice.generate_sifen_pdf'),
    path('consult_invoice_batch_sifen/<int:pk>/', InvoiceConsultBatchToSifenView.as_view(), name='invoice.consult_invoice_batch_sifen'),

    path('show_invoice_html/<int:pk>/', InvoiceShowHtmlView.as_view(), name='invoice.show_invoice_html'),
    path('generate_invoice_html_sifen/<int:pk>/', InvoiceGenerateSifenHtmlView.as_view(), name='invoice.generate_sifen_html'),
    path('print_invoice_preview_html/<int:pk>/', PrintInvoicePreviewHtmlView.as_view(), name='invoice.print_invoice_preview_html'),

    # CCREDIT NOTE
    path('credit_note/list/', CreditNoteDataTableView.as_view(), name='credit_note_list'),
    path('credit_note/details/<int:pk>', CreditNoteDetailsView.as_view(), name='credit_note_detail'),
    path('credit_note/create/', CreditNoteCreationView.as_view(), name='credit_note_create'),
    path('credit_note/create_from_invoice/<int:invoice_header_id>/', CreditNoteCreationFromInvoiceView.as_view(), name='credit_note.create_from_invoice'),
    path('credit_note/delete/<int:pk>/', CreditNoteDeleteView.as_view(), name='credit_note_delete'),
    path('credit_note/modify/<int:pk>/', CreditNoteUpdateView.as_view(), name='credit_note_update'),
    path('credit_note/print/<int:pk>/', CreditNotePrintView.as_view(), name='credit_note.print'),

    path('send_credit_note_to_sifen/<int:pk>/', CreditNoteSendToSifenView.as_view(), name='credit_note.send_to_sifen'),
    path('generate_credit_note_pdf_sifen/<int:pk>/', CreditNoteGenerateSifenPdfView.as_view(), name='credit_note.generate_sifen_pdf'),
    path('download_credit_note_pdf/<int:pk>/', CreditNoteDownloadPdfview.as_view(), name='credit_note.download_pdf'),
    path('consult_credit_note_batch_sifen/<int:pk>/', CreditNoteConsultBatchToSifenView.as_view(), name='credit_note.consult_credit_note_batch_sifen'),
    path('send_credit_note_email_to_cliente/<int:pk>/', CreditNoteEmailSendToClientView.as_view(), name='credit_note.email_send_to_client'),
    path('get_last_credit_note_number/<int:company_id>/', CreditNoteGetLastNumberView.as_view(), name='credit_note.get_last_number'),

    path('get_invoice_data_json/<int:invoice_id>/', GetInvoiceDataJsonView.as_view(), name='invoice.get_invoice_data_json'),
    path('get_invoices_by_company_json/<int:company_id>/', GetInvoicesByCompanyJsonView.as_view(), name='invoice.get_invoices_by_company_json'),

    path('generate_credit_note_html_sifen/<int:pk>/', CreditNoteGenerateSifenHtmlView.as_view(), name='credit_note.generate_sifen_html'),
    path('show_credit_note_html/<int:pk>/', CreditNoteShowHtmlView.as_view(), name='credit_note.show_credit_note_html'),

    # RUC Validation
    path('validate_ruc_set/<str:ruc_str>/', ValidateRucSetView.as_view(), name='validate_ruc_set'),

    # CUSTOMER
    path('customer/list/', CustomerDataTableView.as_view(), name='invoicing.customer_list'),
    path('customer/create/', CustomerCreateView.as_view(), name='invoicing.customer_create'),
    path('customer/update/<int:pk>', CustomerUpdateView.as_view(), name='invoicing.customer_update'),
    path('customer/delete/<int:pk>', CustomerDeleteView.as_view(), name='invoicing.customer_delete'),
    path('customer/details/<int:pk>', CustomerDetailView.as_view(), name='invoicing.customer_detail'),


]

sistema/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from sistema import settings

admin.site.site_header = "Sistema Iribas Admin"
admin.site.site_title = "Sistema Iribas Portal"
admin.site.index_title = "Bienvenido al administrador del Sistema Iribas"

urlpatterns = [
                  path('admin/', admin.site.urls,),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('base.urls')),
              ]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'sistema.views.handler404'
# handler500 = 'sistema.views.handler500'

invoicing/models.py
from django.contrib.auth.models import User
from django.db import models
from softdelete.models import SoftDeleteObject
from django.utils.translation import ugettext_lazy as _
from auditlog.registry import auditlog
from base.models import Person, Currency, TimeStampModel

# Create your models here.
# Company Name
from clinic.models import Patient


class Customer(SoftDeleteObject, TimeStampModel):
    INDIVIDUAL = 0
    LEGAL_ENTITY = 1

    CUSTOMER_TYPES = (
        (INDIVIDUAL, _("Individual")),
        (LEGAL_ENTITY, _("Legal Entity"))
    )
    customer_name = models.CharField(verbose_name=_('Customer Name'),
                                     max_length=40, null=False, blank=False)
    customer_tax_id_number = models.CharField(verbose_name=_('Customer Tax Identification Number'),
                                              max_length=40, null=False, blank=False, unique=True)
    patient = models.ForeignKey(to=Patient, on_delete=models.PROTECT,
                                null=True, blank=True)

    customer_email = models.EmailField(verbose_name=_('Customer Email'),
                                       null=True, blank=False)
    customer_address = models.CharField(verbose_name=_('Customer Address'),
                                        max_length=250, null=True, blank=False)
    customer_phone_number = models.CharField(verbose_name=_('Customer Phone Number'),
                                             max_length=20, null=True, blank=False)
    sifen_ruc_validated = models.BooleanField(
        verbose_name=_('Sifen RUC Validated'), default=False, null=True, blank=True
    )
    is_taxpayer = models.BooleanField(
        verbose_name=_('Is Taxpayer'), default=True, null=True, blank=False
    )
    customer_type = models.IntegerField(
        verbose_name=_('Customer Type'),
        null=True, blank=False,
        choices=CUSTOMER_TYPES,
        default=0
    )

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

    def __str__(self):
        if self.customer_tax_id_number:
            return self.customer_name + " (" + self.customer_tax_id_number + ")"
        else:
            return self.customer_name


class IssuingCompanyName(SoftDeleteObject, TimeStampModel):
    company_name = models.CharField(verbose_name=_('Company Name'),
                                    max_length=40, null=False, blank=False, unique=True)
    company_tax_id = models.CharField(verbose_name=_('Client Tax Identification Number'),
                                      max_length=50, null=False, blank=False, unique=True)

    # SIFEN CLIENT PARAMS
    sifen_logo = models.CharField(verbose_name=_('SIFEN LOGO'), blank=False, null=True, max_length=200)
    sifen_password = models.CharField(verbose_name=_('SIFEN PASSWORD'), blank=False, null=True, max_length=100)
    sifen_id_csc = models.CharField(verbose_name=_('SIFEN ID CSC'), blank=False, null=True, max_length=100)
    sifen_csc = models.CharField(verbose_name=_('SIFEN CSC'), blank=False, null=True, max_length=200)

    # SIFEN PARAMS
    sifen_digital_signature_date = models.CharField(verbose_name=_('SIFEN DIGITAL SIGNATURE DATE'),
                                                    blank=False, null=True, max_length=100)
    sifen_ruc = models.CharField(verbose_name=_('SIFEN RUC'), blank=False, null=True, max_length=100)
    sifen_business_name = models.CharField(verbose_name=_('SIFEN BUSINESS NAME'), blank=False,
                                           null=True, max_length=200)
    sifen_fantasy_name = models.CharField(verbose_name=_('SIFEN FANTASY NAME'), blank=False,
                                          null=True, max_length=200)

    # SIFEN PARAMS - ECONOMIC ACTIVITY
    sifen_economic_activity_code = models.CharField(verbose_name=_('SIFEN ECONOMIC ACTIVITY CODE'), blank=False,
                                                    null=True, max_length=10)
    sifen_economic_activity_description = models.CharField(verbose_name=_('SIFEN ECONOMIC ACTIVITY DESCRIPTION'),
                                                           blank=False, null=True, max_length=200)
    sifen_stamp_number = models.CharField(verbose_name=_('SIFEN STAMP NUMBER'), blank=False, null=True, max_length=200)
    sifen_stamp_date = models.CharField(verbose_name=_('SIFEN STAMP DATE'), blank=False, null=True, max_length=100)

    # PARAMS - ESTABLISHMENT
    sifen_establishment_code = models.CharField(verbose_name=_('SIFEN ESTABLISHMENT CODE'),
                                                blank=False, null=True, max_length=4)
    sifen_establishment_direction = models.CharField(verbose_name=_('SIFEN ESTABLISHMENT DIRECTION'),
                                                     blank=False, null=True, max_length=200)
    sifen_establishment_house_number = models.CharField(verbose_name=_('SIFEN ESTABLISHMENT HOUSE NUMBER'),
                                                        blank=False, null=True, max_length=200)
    sifen_establishment_street_name_1 = models.CharField(verbose_name=_('SIFEN ESTABLISHMENT STREET NAME 1'),
                                                         blank=False, null=True, max_length=200)
    sifen_establishment_street_name_2 = models.CharField(verbose_name=_('SIFEN ESTABLISHMENT STREET NAME 2'),
                                                         blank=False, null=True, max_length=200)
    sifen_establishment_department_code = models.CharField(verbose_name=_('SIFEN ESTABLISHMENT DEPARTMENT CODE'),
                                                           blank=False, null=True, max_length=3)
    sifen_establishment_department_description = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT DEPARTMENT DESCRIPTION'), blank=False, null=True, max_length=200)
    sifen_establishment_district_code = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT DISTRICT CODE'), blank=False, null=True, max_length=3)
    sifen_establishment_district_description = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT DISTRICT DESCRIPTION'), blank=False, null=True, max_length=200)
    sifen_establishment_city_code = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT CITY CODE'), blank=False, null=True, max_length=3)
    sifen_establishment_city_description = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT CITY DESCRIPTION'), blank=False, null=True, max_length=50)
    sifen_establishment_phone = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT PHONE'), blank=False, null=True, max_length=12)
    sifen_establishment_email = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT EMAIL'), blank=False, null=True, max_length=100)
    sifen_establishment_denomination = models.CharField(
        verbose_name=_('SIFEN ESTABLISHMENT DENOMINATION'), blank=False, null=True, max_length=200)

    # SIFEN - EMAIL SENDER
    sifen_email_host = models.CharField(verbose_name=_('SIFEN EMAIL HOST'), blank=False, null=True, max_length=100)
    sifen_email_port = models.CharField(verbose_name=_('SIFEN EMAIL PORT'), blank=False, null=True, max_length=5)
    sifen_email_host_user = models.CharField(verbose_name=_('SIFEN EMAIL HOST USER'),
                                             blank=False, null=True, max_length=100)
    sifen_email_host_password = models.CharField(verbose_name=_('SIFEN EMAIL HOST PASSWORD'),
                                                 blank=False, null=True, max_length=100)
    sifen_email_use_tls = models.BooleanField(verbose_name=_('SIFEN EMAIL USE TLS'), null=False, default=True)
    sifen_email_default_from = models.CharField(verbose_name=_('SIFEN EMAIL DEFAULT FROM'),
                                                blank=False, null=True, max_length=200)

    class Meta:
        verbose_name = _('Issuing Company')
        verbose_name_plural = _('Issuing Companys')

    def __str__(self):
        return self.company_name


# Invoice Stamp
class InvoiceStamp(SoftDeleteObject, TimeStampModel):
    startDate = models.DateField(verbose_name=_('Start Date'))
    endDate = models.DateField(verbose_name=_('End Date'))
    number = models.CharField(max_length=30, verbose_name=_('Number'))
    company_name = models.ForeignKey(to=IssuingCompanyName, on_delete=models.PROTECT,
                                     null=True, blank=True,
                                     verbose_name=_('Company Name'),
                                     related_name='company')
    electronic_stamp = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('Invoice Stamp')
        verbose_name_plural = _('Invoice Stamps')

    def as_json(self):
        return dict(
            label=self.number,
            numero=self.number,
            id=self.id
        )

    def __str__(self):
        return self.number + " - " + str(self.company_name)


auditlog.register(InvoiceStamp)


# Credit Note Stamp
class CreditNoteStamp(SoftDeleteObject, TimeStampModel):
    startDate = models.DateField(verbose_name=_('Start Date'))
    endDate = models.DateField(verbose_name=_('End Date'))
    number = models.CharField(max_length=30, verbose_name=_('Number'))
    company_name = models.ForeignKey(to=IssuingCompanyName, on_delete=models.PROTECT,
                                     null=True, blank=True,
                                     verbose_name=_('Company Name'),
                                     related_name='credit_note_stamps')
    electronic_stamp = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('Credit Note Stamp')
        verbose_name_plural = _('Credit Note Stamps')

    def as_json(self):
        return dict(
            label=self.number,
            numero=self.number,
            id=self.id
        )

    def __str__(self):
        return self.number + " - " + str(self.company_name)


auditlog.register(InvoiceStamp)


class InvoiceRange(SoftDeleteObject, TimeStampModel):

invoicing/templates/invoicing/customer/customer_create.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url "invoicing.customer_list" %}">Cliente</a>
    </h1>

{% endblock %}
{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Crear Cliente</h6>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {{ form.customer_name|as_crispy_field }}
                {{ form.customer_tax_id_number|as_crispy_field }}
                {{ form.customer_email|as_crispy_field }}
                {{ form.customer_address|as_crispy_field }}
                {{ form.customer_phone_number|as_crispy_field }}
                {{ form.is_taxpayer|as_crispy_field }}
                {{ form.customer_type|as_crispy_field }}
                {{ form.patient|as_crispy_field }}

                <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Guardar">
                <a class="btn btn-sm btn-light shadow-sm" href="{% url 'invoicing.customer_list' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link href="{% static 'build/vendor/chosen-js/chosen.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'build/vendor/chosen-js/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'build/vendor/moment/moment.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-mask-plugin/jquery.mask.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-formset/jquery.formset.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            $('#id_patient').chosen();

        });
    </script>

{% endblock %}

invoicing/templates/invoicing/customer/customer_delete.html
{% extends "layout.html" %}
{% load static %}
{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    <a href="{% url 'invoicing.customer_list' %}">Clientes</a>
  </h1>
{% endblock %}
{% block content %}
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Eliminar cliente</h6>
    </div>
    <div class="card-body">
      <p>Está seguro que quiere eliminar este cliente? </p>
      <span><b>{{ customer.id }} - {{ customer.customer_name }} - {{ customer.customer_tax_id_number }}</b></span>
      <br><br>
      <form method="post" enctype="multipart/form-data" action="{% url 'invoicing.customer_delete' customer.id %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Confirmar">
        <a class="btn btn-sm btn-light shadow-sm" href="{% url 'invoicing.customer_list' %}">Volver a Lista de clientes</a>
      </form>
    </div>
  </div>
{% endblock %}

invoicing/templates/invoicing/customer/customer_detail.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url 'invoicing.customer_list' %}">Clientes</a>
    </h1>

{% endblock %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Detalles de cliente: {{ customer.id }}</h6>
        </div>
        <div class="card-body">
            <div id="invoice">
                <div class="invoice overflow-auto">
                    <div style="min-width: 600px" class="container">
                        <div class="p-2 col-8 bd-highlight">
                            <div class="p-1 bd-highlight text-end">
                                <b>Nombre o Razón Social:</b> {{ customer.customer_name }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>RUC:</b> {{ customer.customer_tax_id_number }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>Email:</b> {{ customer.customer_email }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>Nro de Teléfono:</b> {{ customer.customer_phone_number }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>Dirección:</b> {{ customer.customer_address }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>Es Contribuyente:</b> {{ customer.is_taxpayer|yesno:"Si, No" }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>Tipo de Cliente:</b> {{ customer.get_customer_type_display }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>RUC validado por la SET:</b> {{ customer.sifen_ruc_validated|yesno:"Si, No" }}
                            </div>
                            <div class="p-1 bd-highlight text-end">
                                <b>Paciente Relacionado:</b> {{ customer.patient|default_if_none:"---" }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="{% url 'invoicing.customer_update' customer.id %}" class="btn btn-primary btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-pencil-alt"></i>
                                        </span>
                <span class="text">Editar Cliente</span>
            </a>
            <a href="{% url 'invoicing.customer_delete' customer.id %}" class="btn btn-danger btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-trash"></i>
                                        </span>
                <span class="text">Eliminar Cliente</span>
            </a>
            <a href="{% url 'invoicing.customer_list' %}" class="btn btn-light btn-icon-split">
            <span class="icon text-gray-600">
                <i class="fas fa-arrow-right"></i>
            </span>
                <span class="text">Volver al Listado</span>
            </a>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <!-- Custom styles for this page -->
    <link href="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block extra_js %}
    <!-- Page level plugins -->
    <script src="{% static 'build/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'base/js/datatables/numeric-comma.js' %}"></script>


{% endblock %}

invoicing/templates/invoicing/customer/customer_list.html
{% extends "layout.html" %}

{% load static %}

{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    Clientes
  </h1>

{% endblock %}
{% block content %}

  <!-- DataTables Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes <a href="{% url 'invoicing.customer_create' %}" class="btn btn-info btn-circle">
        <i class="fas fa-plus"></i></a>
      </h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        {{ datatable }}
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_css %}
  <!-- Custom styles for this page -->
  <link href="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block extra_js %}
  <!-- Page level plugins -->
  <script src="{% static 'build/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'base/js/datatables/numeric-comma.js' %}"></script>
  <script type="text/javascript" charset="utf8" src="{% static 'invoicing/js/datatableview.js' %}"></script>

  <!-- Page level custom scripts -->
  <script type="text/javascript">
    $(function (){
        $('#sidebarToggle').trigger('click');

        /* se inicializa el datatables */
        datatableview.initialize($('.datatable'),
            /* Archivo de traducción */
            {
                language: {
                    url: "{% url 'datatables_translation' %}",
                },

                columnDefs: [{
                    width: "150px",
                    targets: 0
                  },
                ]
            }
        );
    });

  </script>


{% endblock %}

invoicing/templates/invoicing/customer/customer_update.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url 'invoicing.customer_list' %}">Clientes</a>
    </h1>

{% endblock %}
{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Actualizar Cliente</h6>
        </div>
        <div class="card-body">
            <form id="update_invoice_form" method="POST">
                {% csrf_token %}
                {{ form.customer_name|as_crispy_field }}
                {{ form.customer_tax_id_number|as_crispy_field }}
                {{ form.customer_email|as_crispy_field }}
                {{ form.customer_address|as_crispy_field }}
                {{ form.customer_phone_number|as_crispy_field }}
                {{ form.is_taxpayer|as_crispy_field }}
                {{ form.customer_type|as_crispy_field }}
                {{ form.patient|as_crispy_field }}

                <input type="submit" class="btn btn-success" value="Guardar Cambios">

                <a class="btn btn-light btn-icon-split" href="{% url 'invoicing.customer_list' %}">
            <span class="icon text-gray-600">
                <i class="fas fa-arrow-right"></i>
            </span>
                    <span class="text">Cancelar</span>
                </a>
            </form>
        </div>
    </div>
{% endblock %}
{% block extra_css %}
    <link href="{% static 'build/vendor/chosen-js/chosen.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'build/vendor/chosen-js/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'build/vendor/moment/moment.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-mask-plugin/jquery.mask.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-formset/jquery.formset.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            $('#id_patient').chosen();

        });
    </script>

{% endblock %}