base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Base
import stock
from base import views
from base.views import DashboardView, DataTablesTranslationsJsonView

# Clinic
import clinic
from clinic import urls

# Scheduling
import scheduling
from scheduling import urls

# Consultation
import consultation
from consultation import urls

# Stock
import stock
from stock import urls

# Invoicing
import invoicing
from invoicing import urls

# Reports
import reports.urls


urlpatterns = [
    # Base URLs
    path('login/', views.Login.as_view(), name='login'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Datatables translation
    path('datatables_translation', DataTablesTranslationsJsonView.as_view(), name='datatables_translation'),

    # Clinic URLs
    path('clinic/', include(clinic.urls)),

    # Scheduling URLs
    path('scheduling/', include(scheduling.urls)),

    # Consultation URLs
    path('consultation/', include(consultation.urls)),

    # Stock URLs
    path('stock/', include(stock.urls)),

    # Invoicing URLs
    path('invoicing/', include(invoicing.urls)),

    # Reports URLs
    path('reports/', include(reports.urls)),

]

clinic/urls.py
from django.urls import path

from clinic.views import PatientListView, PatientDetailView, PatientDetailJsonView, \
    PatientUpdateView, PatientCreateView, PatientDeleteView, MedicalStudyDetailJsonView, \
    MedicalEquipmentListByStudyJsonView, DoctorListByStudyJsonView, MedicalEquipmentListAllJsonView, \
    DoctorListAllJsonView, PatientDataTableView, PatientDetailAutocompleteJsonView, \
    MedicalStudyAutocompleteDetailJsonView

urlpatterns = [
    # Patient
    path('patient/list/', PatientDataTableView.as_view(), name='patient.list'),
    path('patient/list_datatable/', PatientDataTableView.as_view(), name='patient.list_datatable'),
    path('patient/detail/<int:pk>/', PatientDetailView.as_view(), name='patient.detail'),
    path('patient/detail_json/<int:pk>/', PatientDetailJsonView.as_view(), name='patient.detail_json'),
    path('patient/detail_autocomplete_json/', PatientDetailAutocompleteJsonView.as_view(), name='patient.detail_autocomplete_json'),
    path('patient/create/', PatientCreateView.as_view(), name='patient.create'),
    path('patient/delete/<int:pk>/', PatientDeleteView.as_view(), name='patient.delete'),
    path('patient/update/<int:pk>/', PatientUpdateView.as_view(), name='patient.update'),

    # Medical Study
    path('medical_study/detail_json/<int:pk>/', MedicalStudyDetailJsonView.as_view(), name='medical_study.detail_json'),
    path('medical_study/autocomplete_detail_json/', MedicalStudyAutocompleteDetailJsonView.as_view(), name='medical_study.autocomplete_detail_json'),

    # Medical Equipment
    path('medical_equipment/get_list_by_study_json/<int:pk>/', MedicalEquipmentListByStudyJsonView.as_view(), name='medical_equipment.list_by_study_json'),
    path('medical_equipment/get_list_all_json/', MedicalEquipmentListAllJsonView.as_view(), name='medical_equipment.list_all_json'),

    # Doctor
    path('doctor/get_list_by_study_json/<int:pk>/', DoctorListByStudyJsonView.as_view(), name='doctor.list_by_study_json'),
    path('doctor/get_list_all_json/', DoctorListAllJsonView.as_view(), name='doctor.list_all_json'),
]

sistema/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from sistema import settings

admin.site.site_header = "Sistema Iribas Admin"
admin.site.site_title = "Sistema Iribas Portal"
admin.site.index_title = "Bienvenido al administrador del Sistema Iribas"

urlpatterns = [
                  path('admin/', admin.site.urls,),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('base.urls')),
              ]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'sistema.views.handler404'
# handler500 = 'sistema.views.handler500'

base/models.py
from datetime import date

from auditlog.registry import auditlog
from dateutil import relativedelta
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from softdelete.models import SoftDeleteObject


# Create your models here.
class TimeStampModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated at')
    )

    class Meta:
        abstract = True


# PERSON
class Person(models.Model):

    CITYS = (
        (1, "ASUNCION"),
        (2, "FUERTE OLIMPO"),
        (3, "LA VICTORIA"),
        (4, "MCAL ESTIGARRIBIA"),
        (5, "FILADELFIA"),
        (6, "LOMA PLATA"),
        (7, "JOSE FALCON"),
        (8, "NANAWA"),
        (9, "VILLA HAYES"),
        (10, "BENJAMIN ACEVAL"),
        (11, "PINASCO"),
        (12, "CORPUS CHRISTI"),
        (13, "CURUGUATY"),
        (14, "FRANCISCO CABALLERO A"),
        (15, "ITANARA"),
        (16, "KATUETE"),
        (17, "LA PALOMA"),
        (18, "NUEVA ESPERANZA"),
        (19, "SALTOS DEL GUAIRA"),
        (20, "YGATIMI"),
        (21, "YPEJHU"),
        (22, "PEDRO J CABALLERO"),
        (23, "CAPITAN BADO"),
        (24, "BELLA VISTA NORTE"),
        (25, "ALBERDI"),
        (26, "CERRITO"),
        (27, "DESMOCHADOS"),
        (28, "GRAL DIAZ"),
        (29, "GUAZU CUA"),
        (30, "HUMAITA"),
        (31, "ISLA UMBU"),
        (32, "LAURELES"),
        (33, "MAYOR MARTINEZ"),
        (34, "PASO DE PATRIA"),
        (35, "PILAR"),
        (36, "SAN JUAN NEEMBUCU"),
        (37, "TACUARAS"),
        (38, "VILLA FRANCA"),
        (39, "VILLA OLIVA"),
        (40, "VILLALBIN"),
        (41, "AREGUA"),
        (42, "CAPIATA"),
        (43, "FERNANDO DE LA MORA"),
        (44, "GUARAMBARE"),
        (45, "ITA"),
        (46, "ITAUGUA"),
        (47, "J A SALDIVAR"),
        (48, "LAMBARE"),
        (49, "LIMPIO"),
        (50, "LUQUE"),
        (51, "MARIANO R ALONSO"),
        (52, "NUEVA ITALIA"),
        (53, "NEMBY"),
        (54, "SAN ANTONIO"),
        (55, "SAN LORENZO"),
        (56, "VILLA ELISA"),
        (57, "VILLETA"),
        (58, "YPACARAI"),
        (59, "YPANE"),
        (60, "LOS CEDRALES"),
        (61, "CIUDAD DEL ESTE"),
        (62, "DOMINGO M IRALA"),
        (63, "HERNANDARIAS"),
        (64, "IRUNA"),
        (65, "ITAKYRY"),
        (66, "MBARACAYU"),
        (67, "MINGA GUAZU"),
        (68, "MINGA PORA"),
        (69, "NARANJAL"),
        (70, "NACUNDAY"),
        (71, "JUAN E OLEARY"),
        (72, "PTE FRANCO"),
        (73, "SAN ALBERTO"),
        (74, "SAN CRISTOBAL"),
        (75, "SANTA RITA"),
        (76, "SANTA ROSA MONDAY"),
        (77, "YGUAZU"),
        (78, "ACAHAY"),
        (79, "CAAPUCU"),
        (80, "CABALLERO"),
        (81, "CARAPEGUA"),
        (82, "ESCOBAR"),
        (83, "LA COLMENA"),
        (84, "MBUYAPEY"),
        (85, "PARAGUARI"),
        (86, "PIRAYU"),
        (87, "QUIINDY"),
        (88, "QUYQUYHO"),
        (89, "ROQUE GONZALEZ"),
        (90, "SAPUCAI"),
        (91, "TEBICUARYMI"),
        (92, "YAGUARON"),
        (93, "YBYCUI"),
        (94, "YBYTYMI"),
        (95, "VILLA FLORIDA"),
        (96, "SAN MIGUEL"),
        (97, "SAN JUAN BAUTISTA"),
        (98, "SANTA MARIA"),
        (99, "SAN IGNACIO"),
        (100, "SANTA ROSA MISIONES"),
        (101, "SAN PATRICIO"),
        (102, "SANTIAGO"),
        (103, "AYOLAS"),
        (104, "YABEBYRY"),
        (105, "ALTO VERA"),
        (106, "BELLA VISTA SUR"),
        (107, "CAMBYRETA"),
        (108, "CAPITAN MEZA"),
        (109, "CAPITAN MIRANDA"),
        (110, "CARLOS A LOPEZ"),
        (111, "CARMEN PARANA"),
        (112, "CNEL BOGADO"),
        (113, "EDELIRA"),
        (114, "ENCARNACION"),
        (115, "FRAM"),
        (116, "ARTIGAS"),
        (117, "GRAL DELGADO"),
        (118, "HOHENAU"),
        (119, "ITAPUA POTY"),
        (120, "JESUS"),
        (121, "LA PAZ"),
        (122, "LEANDRO OVIEDO"),
        (123, "NATALIO"),
        (124, "NUEVA ALBORADA"),
        (125, "OBLIGADO"),
        (126, "MAYOR OTANO"),
        (127, "PIRAPO"),
        (128, "SAN COSME Y DAMIAN"),
        (129, "SAN JUAN PARANA"),
        (130, "SAN PEDRO PARANA"),
        (131, "SAN RAFAEL DEL PARANA"),
        (132, "TOMAS ROMERO PEREIRA"),
        (133, "TRINIDAD"),
        (134, "YATYTAY"),
        (135, "ABAI"),
        (136, "BERTONI"),
        (137, "BUENA VISTA"),
        (138, "CAAZAPA"),
        (139, "MACIEL"),
        (140, "GRAL MORINIGO"),
        (141, "SAN JUAN NEPOMUCENO"),
        (142, "TAVAI"),
        (143, "YEGROS"),
        (144, "YUTY"),
        (145, "3 DE FEBRERO"),
        (146, "CAAGUAZU"),
        (147, "CARAYAO"),
        (148, "CECILIO BAEZ"),
        (149, "CNEL OVIEDO"),
        (150, "JOSE D OCAMPOS"),
        (151, "J E ESTIGARRIBIA"),
        (152, "JUAN M FRUTOS"),
        (153, "LA PASTORA"),
        (154, "MCAL LOPEZ"),
        (155, "NUEVA LONDRES"),
        (156, "RI3 CORRALES"),
        (157, "RAUL A OVIEDO"),
        (158, "REPATRIACION"),
        (159, "SAN JOAQUIN"),
        (160, "SAN JOSE ARROYOS"),
        (161, "SIMON BOLIVAR"),
        (162, "SANTA ROSA MBUTUY"),
        (163, "VAQUERIA"),
        (164, "YHU"),
        (165, "BORJA"),
        (166, "DR BOTRELL"),
        (167, "CNEL MARTINEZ"),
        (168, "COL INDEPENDENCIA"),
        (169, "FELIX PEREZ CARDOZO"),
        (170, "GRAL GARAY"),
        (171, "ITAPE"),
        (172, "ITURBE"),
        (173, "FASSARDI"),
        (174, "MBOCAYATY"),
        (175, "NATALICIO TALAVERA"),
        (176, "NUMI"),
        (177, "PASO YOBAI"),
        (178, "SAN SALVADOR"),
        (179, "TROCHE"),
        (180, "VILLARRICA"),
        (181, "YATAITY"),
        (182, "ALTOS"),
        (183, "ARROYOS Y ESTEROS"),
        (184, "ATYRA"),
        (185, "CAACUPE"),
        (186, "CARAGUATAY"),
        (187, "EMBOSCADA"),
        (188, "EUSEBIO AYALA"),
        (189, "ISLA PUCU"),
        (190, "ITACURUBI CORDILLERA"),
        (191, "JUAN DE MENA"),
        (192, "LOMA GRANDE"),
        (193, "MBOCAYATY DEL YHAGUY"),
        (194, "NUEVA COLOMBIA"),
        (195, "PIRIBEBUY"),
        (196, "PRIMERO DE MARZO"),
        (197, "SAN BERNARDINO"),
        (198, "SAN JOSE OBRERO"),
        (199, "SANTA ELENA"),
        (200, "TOBATI"),
        (201, "VALENZUELA"),
        (202, "25 DE DICIEMBRE"),
        (203, "ANTEQUERA"),
        (204, "GRAL AQUINO"),
        (205, "CAPIIBARY"),
        (206, "CHORE"),
        (207, "GRAL RESQUIN"),
        (208, "GUAYAIBI"),
        (209, "ITACURUBI ROSARIO"),
        (210, "LIMA"),
        (211, "NUEVA GERMANIA"),
        (212, "SAN ESTANISLAO"),
        (213, "SAN PABLO"),
        (214, "SAN PEDRO YCUAMANDYYU"),
        (215, "SANTA ROSA DEL AGUARAY"),
        (216, "TACUATI"),
        (217, "UNION"),
        (218, "VILLA DEL ROSARIO"),
        (219, "YATAITY DEL NORTE"),
        (220, "SAN LAZARO"),
        (221, "BELEN"),
        (222, "CONCEPCION"),
        (223, "HORQUETA"),
        (224, "LORETO"),
        (225, "SAN CARLOS"),
        (226, "YBY YAU"),
        (227, "JUAN LEON MALLORQUIN"),
        (228, "AZOTE Y"),
        (229, "ZANJA PYTA"),
        (230, "SGTO.JOSE FELIX LOPEZ"),
        (231, "BAHIA NEGRA"),
        (232, "TTE 1 IRALA FERNANDEZ"),
        (233, "TTE.ESTEBAN MARTINEZ"),
        (234, "GRAL.BRUGUEZ"),
        (235, "LIBERACION"),
        (236, "YRYVU CUA"),
        (237, "YASY KAÑY"),
        (238, "YBYRAROBANA"),
        (239, "NUEVA TOLEDO"),
        (240, "TEMBIAPORA"),
        (241, "TEBICUARY"),
        (242, "TAVAPY"),
        (243, "SANTA FE DEL PARANA"),
        (244, "3 DE MAYO"),
        (245, "CARMELO PERALTA"),
        (246, "RAUL PEÑA"),
    )

    name = models.CharField(
        verbose_name=_('Name'),
        max_length=100,
        blank=False, null=False
    )
    last_name = models.CharField(
        verbose_name=_('Last Name'),
        max_length=100,
        blank=False, null=False
    )
    birth_date = models.DateField(
        verbose_name=_('Birth Date'),
        blank=True, null=True,
    )
    MALE_CODE = 0
    FEMALE_CODE = 1

    SEX_CODES = (
        (MALE_CODE, _('Male')),
        (FEMALE_CODE, _('Female')),
    )
    sex = models.IntegerField(
        verbose_name=_('Sex'),
        choices=SEX_CODES,
        null=False, blank=False
    )
    weight = models.FloatField(
        verbose_name=_('Weight'),
        blank=True, null=True
    )
    email = models.EmailField(
        verbose_name=_('Email'),
        blank=False, null=True
    )
    document_number = models.CharField(
        verbose_name=_('Document Number'),
        unique=True,
        max_length=10,
        blank=False, null=False
    )
    is_taxpayer = models.BooleanField(
        verbose_name=_('Is Taxpayer'), default=True, null=True, blank=False
    )
    tax_identification_name = models.CharField(
        verbose_name=_('Tax Identification Name'),
        max_length=150,
        blank=False, null=True
    )
    tax_identification_number = models.CharField(
        verbose_name=_('Tax Identification Number'),
        max_length=15,
        blank=False, null=True
    )
    address = models.CharField(
        verbose_name=_('Address'),
        max_length=150,
        blank=False, null=True
    )
    city = models.IntegerField(
        verbose_name=_('City'),
        null=True, blank=True,
        choices=CITYS,
        default=1
    )
    phone_number = models.CharField(
        verbose_name=_('Phone Number'),
        max_length=20,
        null=True, blank=False
    )

    class Meta:
        abstract = True

    def calculate_age(self):
        born = self.birth_date
        if born:
            today = date.today()
            delta = relativedelta.relativedelta(today, born)

clinic/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from base.models import Person
from clinic.models import Patient


class PatientForm(forms.ModelForm):
    phone_number = forms.CharField(
        required=True,
        label=_('Phone Number')
    )
    weight = forms.CharField(
        required=True,
        label=_('Weight')
    )
    birth_date = forms.DateField(
        required=True,
        label=_('Birth Date'),
        widget=forms.DateInput(attrs={'placeholder': 'dd/mm/aaaa'}),
    )
    city = forms.ChoiceField(
        required=True,
        label=_('City'),
        choices=Person.CITYS
    )
    address = forms.CharField(
        required=True,
        label=_('address'),
    )

    class Meta:
        model = Patient
        fields = [
            'name',
            'last_name',
            'sex',
            'weight',
            'document_number',

            # invoicing
            'tax_identification_number',
            'tax_identification_name',
            'email',
            'address',
            'phone_number',
            'is_taxpayer',

            'birth_date',
            'city',
            'insurance_plan'
        ]

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'style': 'text-transform: uppercase'})
        self.fields['name'].widget.attrs.update({'class': 'to-upper-case'})

        self.fields['last_name'].widget.attrs.update({'style': 'text-transform: uppercase'})
        self.fields['last_name'].widget.attrs.update({'class': 'to-upper-case'})

        self.fields['address'].widget.attrs.update({'style': 'text-transform: uppercase'})
        self.fields['address'].widget.attrs.update({'class': 'to-upper-case'})

        self.fields['email'].widget.attrs.update({'style': 'text-transform: uppercase'})
        self.fields['email'].widget.attrs.update({'class': 'to-upper-case'})

clinic/templates/patient/patient_create_form.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    <a href="{% url 'patient.list' %}">Pacientes</a>
  </h1>


{% endblock %}
{% block content %}
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Crear Paciente</h6>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data" action="{% url 'patient.create' %}" autocomplete="off">
        {% csrf_token %}
        {% for field in form %}
          {{ field|as_crispy_field }}
        {% endfor %}
        <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Guardar">
        <a class="btn btn-sm btn-light shadow-sm" href="{% url 'patient.list' %}">Cancelar</a>
      </form>
    </div>
  </div>
{% endblock %}

{% block extra_css %}
  <link href="{% static 'build/vendor/chosen-js/chosen.min.css' %}" rel="stylesheet">
  <link href="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
  <script src="{% static 'build/vendor/chosen-js/chosen.jquery.min.js' %}"></script>
  <script src="{% static 'build/vendor/moment/moment.js' %}"></script>
  <script src="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
  <script src="{% static 'build/vendor/jquery-mask-plugin/jquery.mask.min.js' %}"></script>

  <script type="text/javascript">
      $(function () {
          $('#id_birth_date').mask("00/00/0000")
          $('#id_birth_date').click(function (){
              console.log('click en fecha de nacimiento');
              $(this).select();
          });

          /* Datetime picker */
          jQuery.datetimepicker.setLocale('es');

          /* se inicializa los select con chosen */
          $('select').chosen();

          $('.to-upper-case').keyup(function (){
              $(this).val( $(this).val().toUpperCase() );
          });

          $('#id_birth_date').datetimepicker({
              i18n: {
                  es: {
                      months: [
                          'Enero', 'Febrero', 'Marzo', 'Abril',
                          'Mayo', 'Junio', 'Julio', 'Agosto',
                          'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                      ],
                      dayOfWeek: [
                          "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa",
                      ]
                  }
              },
              datepicker: true,
              timepicker: false,
              lang: 'es',
              locale: 'es',
              format: 'd/m/Y',
              inline: false,
          });

      });


  </script>

{% endblock %}

clinic/templates/patient/patient_delete_confirm.html
{% extends "layout.html" %}
{% load static %}
{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    <a href="{% url 'patient.list' %}">Pacientes</a>
  </h1>
{% endblock %}
{% block content %}
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Eliminar Paciente</h6>
    </div>
    <div class="card-body">
      <p>Está Seguro que quiere eliminar este paciente? </p>
      <span><b>{{ patient.name }} {{ patient.last_name }} - {{ patient.document_number }}</b></span>
      <br><br>
      <form method="post" enctype="multipart/form-data" action="{% url 'patient.delete' patient.id %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Confirmar">
        <a class="btn btn-sm btn-light shadow-sm" href="{% url 'patient.detail' patient.id %}">Cancelar</a>
      </form>
    </div>
  </div>
{% endblock %}

clinic/templates/patient/patient_list.html
{% extends "layout.html" %}

{% load static %}

{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    Pacientes
  </h1>
  <!--<p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
    For more information about DataTables, please visit the <a target="_blank"
                                                               href="https://datatables.net">official DataTables
      documentation</a>.</p>-->

{% endblock %}
{% block content %}

  <!-- DataTables Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Pacientes <a href="{% url 'patient.create' %}" class="btn btn-info btn-circle">
        <i class="fas fa-plus"></i></a>
      </h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr style="text-align: center;">
              <th>ID</th>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Nro. Doc.</th>
              <th>RUC</th>
              <th>Sexo</th>
              <th>Peso</th>
              <th>Teléfono</th>
              <th>Email</th>
              <th>Fecha Nac.</th>
              <th>Ciudad</th>
              <th>Dirección</th>
              <th>Plan de Seguro</th>
              <th style="width:5%; text-align: center;"  data-orderable="false" class="no-column-search">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for patient in patients %}

              <tr style="text-align: center;">
                <td>{{ patient.id }}</td>
                <td>{{ patient.name }}</td>
                <td>{{ patient.last_name }}</td>
                <td>{{ patient.document_number }}</td>
                <td>{{ patient.tax_identification_number|default_if_none:"---" }}</td>
                <td>{{ patient.get_sex_display }}</td>
                <td>{{ patient.weight }}</td>
                <td>{{ patient.phone_number }}</td>
                <td>{{ patient.email|default_if_none:"---" }}</td>
                <td>
                  {%  if patient.birth_date %}
                    <span style="display:none;">{{ patient.birth_date|date:"U"}}</span>
                    {{ patient.birth_date|date:"d/m/Y" }}
                  {% else %}
                    ---
                  {% endif %}
                </td>
                <td>{{ patient.get_city_display|default_if_none:"---" }}</td>
                <td>{{ patient.address|default_if_none:"---" }}</td>
                <td>{{ patient.insurance_plan|default_if_none:"Sin Seguro" }}</td>
                <td style="white-space: nowrap;">
                  <a href="{% url 'patient.detail'  patient.id %}" class="btn btn-info btn-circle">
                    <i class="fas fa-eye"></i>
                  </a>
                  <a href="{% url 'patient.update'  patient.id %}" class="btn btn-info btn-circle">
                    <i class="fas fa-pencil-alt"></i>
                  </a>
                  <!--
                  <a href="#" class="btn btn-danger btn-circle" data-target="#confirmDeleteModal">
                    <i class="fas fa-trash"></i>
                  </a>
                  -->
                </td>
              </tr>
            {% empty %}
              <tr style="text-align: center;">
                <td colspan="11">Sin Registros</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_css %}
  <!-- Custom styles for this page -->
  <link href="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block extra_js %}
  <!-- Page level plugins -->
  <script src="{% static 'build/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'base/js/datatables/numeric-comma.js' %}"></script>

  <!-- Page level custom scripts -->
  <script type="text/javascript">
    $(function (){
        /* se inicializa el datatables */
        $('#dataTable').DataTable(
            /* Archivo de traducción */
            {
                language: {
                    url: "{% url 'datatables_translation' %}",
                },
                columnDefs: [
                    { type: "numeric-comma", targets: [0, 6] },
                ]

            }
        );
    });

  </script>


{% endblock %}

clinic/templates/patient/patient_list_datatable.html
{% extends "layout.html" %}

{% load static %}

{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    Pacientes
  </h1>
  <!--<p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
    For more information about DataTables, please visit the <a target="_blank"
                                                               href="https://datatables.net">official DataTables
      documentation</a>.</p>-->

{% endblock %}
{% block content %}

  <!-- DataTables Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Pacientes <a href="{% url 'patient.create' %}" class="btn btn-info btn-circle">
        <i class="fas fa-plus"></i></a>
      </h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        {{ datatable }}
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_css %}
  <!-- Custom styles for this page -->
  <link href="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block extra_js %}
  <!-- Page level plugins -->
  <script src="{% static 'build/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'base/js/datatables/numeric-comma.js' %}"></script>
  <script type="text/javascript" charset="utf8" src="{% static 'js/datatableview.js' %}"></script>

  <!-- Page level custom scripts -->
  <script type="text/javascript">
    $(function (){
        /* se inicializa el datatables */
        datatableview.initialize($('.datatable'),
            /* Archivo de traducción */
            {
                language: {
                    url: "{% url 'datatables_translation' %}",
                },
                columnDefs: [
                    { type: "numeric-comma", targets: [1, 6] },
                ]

            }
        );
    });

  </script>


{% endblock %}