base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

# Base
import stock
from base import views
from base.views import DashboardView, DataTablesTranslationsJsonView

# Clinic
import clinic
from clinic import urls

# Scheduling
import scheduling
from scheduling import urls

# Consultation
import consultation
from consultation import urls

# Stock
import stock
from stock import urls

# Invoicing
import invoicing
from invoicing import urls

# Reports
import reports.urls


urlpatterns = [
    # Base URLs
    path('login/', views.Login.as_view(), name='login'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Datatables translation
    path('datatables_translation', DataTablesTranslationsJsonView.as_view(), name='datatables_translation'),

    # Clinic URLs
    path('clinic/', include(clinic.urls)),

    # Scheduling URLs
    path('scheduling/', include(scheduling.urls)),

    # Consultation URLs
    path('consultation/', include(consultation.urls)),

    # Stock URLs
    path('stock/', include(stock.urls)),

    # Invoicing URLs
    path('invoicing/', include(invoicing.urls)),

    # Reports URLs
    path('reports/', include(reports.urls)),

]

scheduling/urls.py
from django.urls import path
from scheduling.views import AppointmentListView, AppointmentListForCalendarView, AppointmentCalendarView, \
    AppointmentCreateView, AppointmentUpdateView, AppointmentCancelView, AppointmentDetailView, \
    AppointmentCheckEquipmentAvailabilityView, AppointmentCheckDoctorAvailabilityView, AppointmentsOfTheDayListView, \
    AppointmentDocumentPrintView

urlpatterns = [
    # Appointment
    path('appointment/calendar/', AppointmentCalendarView.as_view(), name='appointment.calendar'),
    path('appointment/list_for_calendar/', AppointmentListForCalendarView.as_view(), name='appointment.list_for_calendar'),
    path('appointment/list/', AppointmentListView.as_view(), name='appointment.list'),
    path('appointment/appointments_of_the_day_list/', AppointmentsOfTheDayListView.as_view(), name='appointment.list_appointments_of_the_day'),
    path('appointment/detail/<int:pk>/', AppointmentDetailView.as_view(), name='appointment.detail'),
    path('appointment/create/', AppointmentCreateView.as_view(), name='appointment.create'),
    path('appointment/update/<int:pk>/', AppointmentUpdateView.as_view(), name='appointment.update'),
    # path('appointment/delete/<int:pk>/', AppointmentDeleteView.as_view(), name='appointment.delete'),
    path('appointment/cancel_appointment/<int:pk>/', AppointmentCancelView.as_view(), name='appointment.cancel_appointment'),
    path('appointment/check_equipment_availability/', AppointmentCheckEquipmentAvailabilityView.as_view(), name='appointment.check_equipment_availability'),
    path('appointment/check_docor_availability/', AppointmentCheckDoctorAvailabilityView.as_view(), name='appointment.check_doctor_availability'),

    path('appointment_document/print_view/<int:pk>/', AppointmentDocumentPrintView.as_view(), name='appointment.document_print'),

]

sistema/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from sistema import settings

admin.site.site_header = "Sistema Iribas Admin"
admin.site.site_title = "Sistema Iribas Portal"
admin.site.index_title = "Bienvenido al administrador del Sistema Iribas"

urlpatterns = [
                  path('admin/', admin.site.urls,),
                  path('i18n/', include('django.conf.urls.i18n')),
                  path('', include('base.urls')),
              ]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'sistema.views.handler404'
# handler500 = 'sistema.views.handler500'

scheduling/models.py
import datetime
import os

from django.contrib.auth.models import User
from django.db import models
from softdelete.models import SoftDeleteObject
from django.utils.translation import ugettext_lazy as _
from auditlog.registry import auditlog

from base.models import Currency, TimeStampModel
from clinic.models import MedicalEquipment, Patient, MedicalStudy, Doctor, InsurancePlan, TreatingDoctor


def appointment_document_storage_path(instance, filename):
    return 'appointments/{0}/documents/{1}'.format(str(instance.appointment.id), filename)

# Create your models here.
# APPOINTMENT STATE
class AppointmentState(SoftDeleteObject, TimeStampModel):
    SCHEDULED_STATE = 0
    FILED_STATE = 1
    CANCELED_STATE = 2
    ABSENT_STATE = 3

    STATES_CODES = (
        (SCHEDULED_STATE, _('Scheduled')),
        (FILED_STATE, _('Filed')),
        (CANCELED_STATE, _('Canceled')),
        (ABSENT_STATE, _('Absent')),
    )
    name = models.CharField(max_length=50, verbose_name=_('Name'), null=False, blank=False)
    state_code = models.IntegerField(
        verbose_name=_('State code'),
        choices=STATES_CODES,
        null=False, blank=False
    )

    class Meta:
        verbose_name = _('Appointment State')
        verbose_name_plural = _('Appointment States')

    def __str__(self):
        return self.name


auditlog.register(AppointmentState)


# Default Doctor Appointment Schedule
class DefaultDoctorAppointmentSchedule(SoftDeleteObject, TimeStampModel):
    DAYS_OF_THE_WEEK = (
        (0, _('Monday')),
        (1, _('Tuesday')),
        (2, _('Wednesday')),
        (3, _('Thursday')),
        (4, _('Friday')),
        (5, _('Saturday')),
        (6, _('Sunday')),
    )
    doctor = models.ForeignKey(
        to=Doctor, on_delete=models.PROTECT,
        null=False, blank=False,
        verbose_name=_('Doctor'),
        related_name='default_doctor_schedules'
    )
    day = models.IntegerField(
        verbose_name=_('Day of the week'),
        choices=DAYS_OF_THE_WEEK,
        null=False, blank=False
    )
    start_time = models.TimeField(
        verbose_name=_('Start Time'),
        null=False, blank=False
    )
    end_time = models.TimeField(
        verbose_name=_('End Time'),
        null=False, blank=False
    )

    class Meta:
        verbose_name = _('Default Doctor Appointment Schedule')
        verbose_name_plural = _('Default Doctor Appointments Schedules')
        unique_together = ('doctor', 'day', 'start_time', 'end_time')

    def __str__(self):
        return str(self.doctor) + ' - ' + str(self.get_day_display()) + ' - ' + str(self.start_time) + ' to ' + str(self.end_time)


auditlog.register(DefaultDoctorAppointmentSchedule)


# SCHEDULE
class Schedule(SoftDeleteObject, TimeStampModel):
    schedule_date = models.DateField(
        verbose_name=_('Schedule Date'),
        null=False, blank=False,
    )
    start_time = models.TimeField(
        verbose_name=_('Start Time'),
        null=False, blank=False
    )
    end_time = models.TimeField(
        verbose_name=_('End Time'),
        null=False, blank=False
    )
    doctor = models.ForeignKey(
        to=Doctor, on_delete=models.PROTECT,
        verbose_name=_('Doctor'),
        null=False, blank=False,
        related_name='schedules'
    )
    canceled = models.BooleanField(
        verbose_name=_('Canceled'),
        default=False
    )

    class Meta:
        verbose_name = _('Schedule')
        verbose_name_plural = _('Schedules')

    def __str__(self):
        return _(self.schedule_date.strftime("%A")) + " " + self.schedule_date.strftime("%d/%m/%Y") + ' - ' + str(self.start_time) + ' to ' + str(self.end_time) + ' - ' + str(self.doctor)

    def delete(self, *args, **kwargs):
        # Set apointment state to Canceled
        self.canceled = True
        self.save()

    def save(self, *args, **kwargs):
        # If is an update
        if self.id:
            original_schedule = Schedule.objects.get(pk=self.id)
            original_start = datetime.datetime.combine(original_schedule.schedule_date, original_schedule.start_time)
            original_end = datetime.datetime.combine(original_schedule.schedule_date, original_schedule.end_time)
            appointments_in_original_schedule = Appointment.objects.filter(
                doctor=original_schedule.doctor,
                appointment_date__range=(original_start, original_end)
            )

            # If the schedule was canceled
            if self.canceled:
                # Cancel all appointmens of the original_schedule schedule range
                for appointment in appointments_in_original_schedule:
                    appointment.set_canceled_state()
                    print("Appointment: " + str(appointment) + ' was CANCELED!')

            # If there is a change in the date
            elif self.schedule_date != original_schedule.schedule_date:
                # Cancel all appointmens of the original_schedule schedule range
                for appointment in appointments_in_original_schedule:
                    appointment.set_canceled_state()
                    print("Appointment: " + str(appointment) + ' was CANCELED!')

            # If there is a change in the time range
            elif self.start_time != original_schedule.start_time or self.end_time != original_schedule.end_time:
                start = datetime.datetime.combine(self.schedule_date, self.start_time)
                end = datetime.datetime.combine(self.schedule_date, self.end_time)
                appointments_in_new_schedule = Appointment.objects.filter(
                    doctor=self.doctor,
                    appointment_date__range=(start, end)
                )

                set1 = set(appointments_in_original_schedule)
                set2 = set(appointments_in_new_schedule)

                missing_appointments = list(sorted(set1 - set2))

                print('missing:', missing_appointments)
                for missing_appointment in missing_appointments:
                    missing_appointment.set_canceled_state()
                    print("Appointment: " + str(missing_appointment) + ' was CANCELED!')

        super(Schedule, self).save(*args, **kwargs)


auditlog.register(Schedule)


# APPOINTMENT
class Appointment(SoftDeleteObject, TimeStampModel):
    patient = models.ForeignKey(
        to=Patient, on_delete=models.PROTECT,
        null=False, blank=False,
        verbose_name=_('Patient'),
        related_name='appointments',
    )
    contact_number = models.CharField(
        verbose_name=_('Contact Number'),
        null=False, blank=False,
        max_length=15
    )
    contact_email = models.EmailField(
        verbose_name=_('Contact Email'),
        null=True, blank=True
    )
    medical_study = models.ForeignKey(
        to=MedicalStudy, on_delete=models.PROTECT,
        null=False, blank=False,
        verbose_name=_('Medical Study'),
        related_name='appointments',
    )
    medical_equipment = models.ForeignKey(
        to=MedicalEquipment, on_delete=models.PROTECT,
        verbose_name=_('Medical Equipment'),
        null=True, blank=True,
        related_name='appointments',
    )
    appointment_date_start = models.DateTimeField(
        verbose_name=_('Appointment date start'),
        null=False, blank=False
    )
    appointment_date_end = models.DateTimeField(
        verbose_name=_('Appointment date end'),
        null=False, blank=False
    )

    doctor = models.ForeignKey(
        to=Doctor, on_delete=models.PROTECT,
        null=True, blank=True,
        verbose_name=_('Doctor'),
        related_name='appointments'
    )
    appointment_state = models.ForeignKey(
        to=AppointmentState, on_delete=models.PROTECT,
        null=False, blank=False,
        verbose_name=_('Appointment State'),
        related_name='appointments'
    )
    insurance_plan = models.ForeignKey(
        to=InsurancePlan, on_delete=models.PROTECT,
        null=True, blank=True,
        verbose_name=_('Insurance Plan'),
        related_name='appointments'
    )
    estimated_cost = models.FloatField(
        verbose_name=_('Estimated Cost'),
        null=True, blank=True,
        default=0
    )
    currency = models.ForeignKey(
        to=Currency, on_delete=models.PROTECT,
        verbose_name=_('Currency'),
        null=False, blank=False,
        related_name='appointments'
    )
    treating_doctor = models.ForeignKey(
        to=TreatingDoctor, on_delete=models.PROTECT,
        verbose_name=_('Treating Doctor'),
        null=True, blank=True,
        related_name='appointments'
    )
    observations = models.TextField(
        verbose_name=_('Observations'),
        null=True, blank=True
    )

    class Meta:
        verbose_name = _('Appointment')
        verbose_name_plural = _('Appointments')

    def __str__(self):
        return 'ID:' + str(self.id) + ' - ' + str(self.patient) + ' - ' + str(self.medical_study) + ' - ' + self.appointment_date_start.strftime("%d/%m/%Y %H:%M") + ' - ' + self.appointment_date_end.strftime("%d/%m/%Y %H:%M")

    def set_canceled_state(self):
        canceled_state = AppointmentState.objects.get(state_code=AppointmentState.CANCELED_STATE)
        self.appointment_state = canceled_state
        self.save()


auditlog.register(Appointment)


class AppointmentStateUserLog(SoftDeleteObject, TimeStampModel):
    appointment = models.ForeignKey(
        to=Appointment, on_delete=models.PROTECT,
        verbose_name=_('Appointment'),
        related_name='appointment_states_user_logs',
        null=False, blank=False
    )
    appointment_state = models.ForeignKey(
        to=AppointmentState, on_delete=models.PROTECT,
        verbose_name=_('Appointment State'),
        related_name='appointment_states_user_logs',
        null=False, blank=False
    )
    user = models.ForeignKey(
        to=User, on_delete=models.PROTECT,
        verbose_name=_('User'),
        related_name='appointment_states_user_logs',

scheduling/templates/appointments/appointment_create.html
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
<div class="modal-header">
  <h5 class="modal-title" id="appointmentModalLabel">Agregar Turno</h5>
  <button class="close" type="button" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
<div class="modal-body ui-front">
  <form id="appointment_form" method="post" contentType="multipart/form-data" enctype="multipart/form-data" action="{% url 'appointment.create' %}" autocomplete="off">
    {% csrf_token %}

    {{ form.appointment_date_start|as_crispy_field }}
    {{ form.appointment_date_end|as_crispy_field }}
    {{ form.patient_autocomplete|as_crispy_field }}
    {{ form.patient|as_crispy_field }}
    <!-- New Patient -->
    {{ form.new_patient|as_crispy_field }}
    {{ form.patient_name|as_crispy_field }}
    {{ form.patient_last_name|as_crispy_field }}
    {{ form.patient_sex|as_crispy_field }}
    {{ form.patient_document_number|as_crispy_field }}

    <!-- Invoicing -->
    {{ form.patient_tax_id_number|as_crispy_field }}
    {{ form.patient_tax_id_name|as_crispy_field }}
    {{ form.patient_is_taxpayer|as_crispy_field }}

    {{ form.patient_weight|as_crispy_field }}
    {{ form.patient_birth_date|as_crispy_field }}
    {{ form.patient_city|as_crispy_field }}

    <!-- Invoicing -->
    {{ form.patient_address|as_crispy_field }}
    {{ form.contact_number|as_crispy_field }}
    {{ form.contact_email|as_crispy_field }}

    {{ form.insurance_plan|as_crispy_field }}
    {{ form.medical_study_autocomplete|as_crispy_field }}
    {{ form.medical_study|as_crispy_field }}
    {{ form.medical_equipment|as_crispy_field }}
    {{ form.doctor|as_crispy_field }}
    {{ form.appointment_state|as_crispy_field }}
    {{ form.estimated_cost|as_crispy_field }}
    {{ form.currency|as_crispy_field }}
    {{ form.treating_doctor|as_crispy_field }}
    <!-- New treating Doctor -->
    {{ form.new_treating_doctor|as_crispy_field }}
    {{ form.treating_doctor_name|as_crispy_field }}
    {{ form.treating_doctor_last_name|as_crispy_field }}
    {{ form.treating_doctor_sex|as_crispy_field }}

    <!-- inicio formset documentos -->
          <div {% if not documents_formset %}style="display: none"{% endif %}>
            <h4>Documentos para el estudio</h4>
            {{ documents_formset.management_form|crispy }}
            <table class="table table-bordered table-hover" id="id-table-documents">
              <tbody>
              {% for document_form in documents_formset.forms %}
                <tr id="{{ document_form.prefix }}-row">
                  {{ document_form.id }}
                  <!-- Document Type -->
                  <td {% if document_form.document_type.errors %}class="has-error"{% endif %}>
                    <div class="col-md-12">
                      {{ document_form.document_type|as_crispy_field }}
                    </div>
                    {% if document_form.document_type.errors %}
                      <span class="help-block">
                          {{ document_form.document_type.errors|join:'. ' }}
                        </span>
                    {% endif %}
                  </td>
                  <!-- File -->
                  <td {% if document_form.file.errors %}class="has-error"{% endif %}>
                    <div class="col-md-12">
                      {{ document_form.file|as_crispy_field }}
                    </div>
                    {% if document_form.file.errors %}
                      <span class="help-block">
                          {{ document_form.file.errors|join:'. ' }}
                        </span>
                    {% endif %}
                  </td>
                  <td class="text-center" style="width:10%;">
                    {{ document_form.DELETE }}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- fin formset documentos -->

    {{ form.observations|as_crispy_field }}

    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
      <button id="save_appointment" class="btn btn-primary" type="button">Guardar</button>
    </div>
  </form>
</div>
{% block extra_css %}
  <!-- Custom styles for this page -->
  <style type="text/css">
      #id_observations {
          height: 100px;
      }
  </style>

{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var documents_formset_prefix = '{{ documents_formset.prefix }}';

        var documents_files = [];

    </script>
{% endblock %}

scheduling/templates/appointments/appointment_document_print.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SISTEMA IRIBAS</title>

  <!-- Custom fonts for this template-->


  <!-- Custom styles for this template-->

  {% block extra_css %}
    <style>
        body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }
        * {
            box-sizing: border-box;
            -moz-box-sizing: border-box;
        }
        .page {
            width: 210mm;
            min-height: 297mm;
            padding: 10mm;
            margin: 10mm auto;
            background: white;
        }

        @page {
            size: A4;
            margin: 0;
        }
        @media print {
            html, body {
                width: 210mm;
                height: 99%;
            }
            .page {
                margin: 0;
                border: initial;
                border-radius: initial;
                width: initial;
                min-height: initial;
                box-shadow: initial;
                background: initial;
                page-break-after: always;
            }
        }
        .page:last-child {
            page-break-after: auto;
        }
    </style>
  {% endblock %}

</head>
<body cz-shortcut-listen="true" style="
    height: 100vh;
">

<!-- Wrapper -->
<div id="wrapper" class="page" style="
    display: flex;
    flex-direction: column;
    align-items: stretch;
    height: 100%;
">
  <img width="100%" src="{{ appointment_document.file.url }}">
</div>
<!-- End Wrapper -->

</body>
</html>
<script type="text/javascript">
  window.print();
</script>

scheduling/templates/appointments/appointment_update.html
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
<div class="modal-header">
  <h5 class="modal-title" id="appointmentModalLabel">Editar Turno ID: {{ appointment.id }} - (Estado: {{ appointment.appointment_state }})</h5>
  <button class="close" type="button" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
<div class="modal-body ui-front">
  <form id="appointment_form" method="post" contentType="multipart/form-data" enctype="multipart/form-data" action="{% url 'appointment.update' appointment.id%}" autocomplete="off">
      {% csrf_token %}

      {{ form.appointment_date_start|as_crispy_field }}
      {{ form.appointment_date_end|as_crispy_field }}
      {{ form.patient_autocomplete|as_crispy_field }}
      {{ form.patient|as_crispy_field }}

      {{ form.patient_tax_id_number|as_crispy_field }}
      {{ form.patient_tax_id_name|as_crispy_field }}
      {{ form.contact_email|as_crispy_field }}
      {{ form.contact_number|as_crispy_field }}
      {{ form.patient_address|as_crispy_field }}
      {{ form.patient_is_taxpayer|as_crispy_field }}


      {{ form.insurance_plan|as_crispy_field }}
      {{ form.medical_study_autocomplete|as_crispy_field }}
      {{ form.medical_study|as_crispy_field }}
      {{ form.medical_equipment|as_crispy_field }}
      {{ form.doctor|as_crispy_field }}
      {{ form.appointment_state|as_crispy_field }}
      {{ form.estimated_cost|as_crispy_field }}
      {{ form.currency|as_crispy_field }}
      {{ form.treating_doctor|as_crispy_field }}

      <!-- inicio formset documentos -->
          <div {% if not documents_formset %}style="display: none"{% endif %}>
            <h4>Documentos para el estudio</h4>
            {{ documents_formset.management_form|crispy }}
            <table class="table table-bordered table-hover" id="id-table-documents">
              <tbody>
              {% for document_form in documents_formset.forms %}
                <tr id="{{ document_form.prefix }}-row">
                  {{ document_form.id }}
                  <!-- Document Type -->
                  <td {% if document_form.document_type.errors %}class="has-error"{% endif %}>
                    <div class="col-md-12">
                      {{ document_form.document_type|as_crispy_field }}
                    </div>
                    {% if document_form.document_type.errors %}
                      <span class="help-block">
                          {{ document_form.document_type.errors|join:'. ' }}
                        </span>
                    {% endif %}
                  </td>
                  <!-- File -->
                  <td {% if document_form.file.errors %}class="has-error"{% endif %}>
                    <div class="col-md-12">
                      {{ document_form.file|as_crispy_field }}
                    </div>
                    {% if document_form.file.errors %}
                      <span class="help-block">
                          {{ document_form.file.errors|join:'. ' }}
                        </span>
                    {% endif %}
                  </td>
                  <td class="text-center" style="width:10%;">
                    {{ document_form.DELETE }}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- fin formset documentos -->

      {{ form.observations|as_crispy_field }}

    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
      {%  if appointment.appointment_state.state_code != 2 and appointment.appointment_state.state_code != 3  %}
        {% if not consultation_sheet %}
          <button class="btn btn-danger" type="button" id="btn_cancel_appointment">Cancelar</button>
          <button id="save_appointment" class="btn btn-primary" type="button">Guardar</button>
          <a href="{% url 'consultation_entry_sheet.create_from_appointment' appointment.id %}" class='btn btn-primary'>Crear Ficha</a>
        {% else %}
          <a href="{% url 'consultation_entry_sheet.detail' consultation_sheet.consultation_entry_sheet.id %}" class='btn btn-primary'>Ver Ficha de Entrada</a>
          <a href="{% url 'consultation_sheet.detail' consultation_sheet.id %}" class='btn btn-primary'>Ver Ficha de Estudio</a>
        {% endif %}
      {% endif %}
    </div>
  </form>
</div>
{% block extra_css %}
  <!-- Custom styles for this page -->
  <style type="text/css">
    #id_observations {
        height: 100px;
    }
  </style>

{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        var documents_formset_prefix = '{{ documents_formset.prefix }}';

        var documents_files = [
          {% for document_form in documents_formset.forms %}
              {% if document_form.initial %}
              '{{ document_form.initial.file.url }}'{% if not forloop.last %},{% endif %}
              {% endif %}
          {% endfor %}
      ];

    </script>
{% endblock %}